{   
    'name': 'GLS Odoo Shipping Integration',
    'category': 'Website',
    'author': "Vraja Technologies",
    'version': '13.0.23.11.2020',
    'summary': """We are providing following modules, Shipping Operations, shipping, odoo shipping integration,odoo shipping connector, dhl express, fedex, ups, gls, usps, stamps.com, shipstation, bigcommerce, easyship, amazon shipping, sendclound, ebay, shopify.""",
    'description': """""",
    'depends': ['delivery'],
    'data': ['views/res_company.xml',
             'views/delivery_carrier_view.xml',
             ],
    'images': ['static/description/GLS_Cover_Image.png'],
    'maintainer': 'Vraja Technologies',
    'website':'www.vrajatechnologies.com',
    'demo': [],
    'installable': True,
    'application': True,
    'auto_install': False,
    'price': '149',
    'currency': 'EUR',
    'license': 'OPL-1',
}
