from . import product_product
from . import product_template
from . import purchase_order
from . import return_order_line
from . import sale_report
from . import stock_picking
from . import stock_move
from . import stock_picking_type
from . import account_move
from . import vendor_return_reason
