{
    'name': 'EG Custom',
    'version': '13.0.1.0.3',
    'category': 'Sales',
    'summery': 'EG Custom Changes',
    'author': '',
    'depends': ['syd_product_proposal', 'syd_commercial_return', 'syd_custom'],
    'data': [
        'security/ir.model.access.csv',
        'security/product_security.xml',
        'data/confirm_po_mail_template.xml',
        'data/auto_confirm_cron.xml',
        'data/custom_config_param.xml',
        'data/custom_server_action_view.xml',
        'wizards/purchase_return_wizard_view.xml',
        'reports/picking_product_small_qvc.xml',
        'reports/small_complete_picking_report.xml',
        'views/stock_barcode_template.xml',
        'views/purchase_order_view.xml',
        'views/stock_picking_view.xml',
        'views/stock_picking_type_view.xml',
        'views/vendor_return_reason_view.xml',
    ],
    'qweb': [
        "static/src/xml/stock_widget_barcode_settings.xml",
    ],
    'license': 'LGPL-3',
    'installable': True,
    'application': True,
    'auto_install': False,
}
