{
    "name": "Custom Milor",
    "version": "13.0.1.12.16",
    "category": "base",
    "author": "SayDigital",
    "website": "https://www.saydigital.it",
    "summary": "Custom Milor",
    "support": "info@saydigital.it",
    "description": """ 
        Custom Milor
    """,
    "depends": [
        "im_livechat",
        "web",
        "product",
        "sale",
        "purchase",
        "stock",
        "purchase_stock",
        "shopify_ept",
        "syd_inventory_extended",
        "syd_approvals",
        "stock_picking_batch",
        "sale_stock",
        "syd_quality",
        "syd_partner_milor",
        "shopify_ept",
        "syd_portal_purchase_chatter",
        "stock_account",
        "stock_barcode",
        "syd_picking_anomaly",
        "syd_closable_order",
        "printnode_base",
        "syd_product_milor"
    ],
    "data": [
             "data/data.xml",
             "data/mail_template.xml",
             "security/ir.model.access.csv",
             "security/security.xml",
             "wizard/wizard.xml",
             "views/views.xml",
             "views/portal_templates.xml",
             "views/stock_barcode_templates.xml",
             "views/res_partner_views.xml",
             'report/reports.xml',
             'report/product_product_templates.xml',
             'report/order_report_templates.xml',
             'report/report_stockpicking_operations.xml',
             'report/purchase_order_templates.xml',
             'report/report_assets_common.xml',
             'report/purchase_report.xml'
    ],
    'qweb': [
        "static/src/xml/qweb_templates.xml",
    ],
    "license": "LGPL-3",
    "installable": True,
    "auto_install": True,
}

